Improve exception handling and logging
vaadin/appsec-kit pull request #40
Opened 2023-06-27 07:31 UTC by tamasmak

Closes #15

2023-07-05 14:00 UTC, heruan requested changes
I added some comments to address, but overall looks good!

Now we need tests for the new logic added for rate limiting, but I don't think we have any test for the OSV service and client at all so it's a good time to add those before merging this.

2023-07-05 14:00 UTC, heruan commented on appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecScanEvent.java
> +
I would avoid having loggers in event objects, as they're purpose is to contain data not doing anything.

2023-07-05 14:10 UTC, heruan reviewed
I just pushed a commit addressing my own comments, in particular simplifying the use of the stream API in [`OpenSourceVulnerabilityService`](https://github.com/vaadin/appsec-kit/pull/40/commits/297900187dc946a7e9bf92178723179128925fe6#diff-e73925028a10e5e99783c84d7ac47ecbc7a3a615079d99799f22ee3aaea10341)

Other changes include:
- move the rate limiter to the client
- return non-optional query results
- remove the logger from the scan event

2023-07-05 14:48 UTC, tamasmak commented on appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java
> +            return Optional.of(response);
Yes, that's true. Probably left there from some early phase.

2023-07-05 14:48 UTC, tamasmak commented on appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java
> +            return Optional.of(vulnerability);
Same comment here.

2023-07-05 14:48 UTC, tamasmak commented on appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityService.java
> +        rateLimiter = new RateLimiter(ratePerSecond);
I agree.

2023-07-05 14:51 UTC, tamasmak commented on appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityService.java
> +        });
Thanks. The solution you committed is really simple and nice.

2023-07-07 16:35 UTC, heruan requested changes
I do not clearly get what it's being tested in `OpenSourceVulnerabilityClientTest`: I would expect tests to validate queries such as verify they're using the correct method, headers and content.

This way of mocking the whole URL API is clever, but I'd avoid that: we want to test our own API, and using URL is an implementation detail. Better go with something like `MockServer` to test that the client sends out correct HTTP requests regardless of what we're using internally to send those.

2023-07-07 16:38 UTC, heruan approved these changes
I pushed a commit that uses `MockServer` to verify the OSV client. Tests now verify the correct use of the API by checking the request method, and content-type. For the batch query request, we should also verify that the request body is valid, but let's do this later.

2023-07-07 16:39 UTC, merged